/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MeRouteImport } from './routes/me'
import { Route as ShareRouteImport } from './routes/share'
import { Route as CreationIdRouteImport } from './routes/creation.$id'
import { Route as MakerHandleRouteImport } from './routes/maker.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationIdRoute = CreationIdRouteImport.update({
  id: '/creation/$id',
  path: '/creation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MakerHandleRoute = MakerHandleRouteImport.update({
  id: '/maker/$handle',
  path: '/maker/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/me': typeof MeRoute
  '/share': typeof ShareRoute
  '/creation/$id': typeof CreationIdRoute
  '/maker/$handle': typeof MakerHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/me': typeof MeRoute
  '/share': typeof ShareRoute
  '/creation/$id': typeof CreationIdRoute
  '/maker/$handle': typeof MakerHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/me': typeof MeRoute
  '/share': typeof ShareRoute
  '/creation/$id': typeof CreationIdRoute
  '/maker/$handle': typeof MakerHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/me'
    | '/share'
    | '/creation/$id'
    | '/maker/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/me'
    | '/share'
    | '/creation/$id'
    | '/maker/$handle'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explore'
    | '/me'
    | '/share'
    | '/creation/$id'
    | '/maker/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  MeRoute: typeof MeRoute
  ShareRoute: typeof ShareRoute
  CreationIdRoute: typeof CreationIdRoute
  MakerHandleRoute: typeof MakerHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation/$id': {
      id: '/creation/$id'
      path: '/creation/$id'
      fullPath: '/creation/$id'
      preLoaderRoute: typeof CreationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maker/$handle': {
      id: '/maker/$handle'
      path: '/maker/$handle'
      fullPath: '/maker/$handle'
      preLoaderRoute: typeof MakerHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  MeRoute: MeRoute,
  ShareRoute: ShareRoute,
  CreationIdRoute: CreationIdRoute,
  MakerHandleRoute: MakerHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
